var todayDate = new Date();
console.log('Today date', todayDate);
console.log(todayDate.getFullYear())
console.log(todayDate.getMonth())
console.log(todayDate.getDate())
console.log(todayDate.getTime())
console.log(todayDate.getHours())
console.log(todayDate.getMinutes())
console.log(todayDate.getSeconds())
console.log(todayDate.getMilliseconds())
console.log(todayDate.getDay())
console.log('================================')
console.log(new Date(0))
console.log(new Date(2019, 8, 19))
console.log(new Date('Oct 10'))
console.log(new Date('Oct 10 2019'))
console.log(new Date())