console.log(`----------join-----------`);
console.log(num_arr.join(' != '));
console.log(genre_arr.join(` & `));
console.log(bool_arr.join(` | `));
console.log(mob_arr.join(` ~ `));
console.log(arr_arr.join(` %%%% `));
console.log(fun_arr.join(` $$ `));
console.log(arr3.join(` ____ `));
console.log(arr4.join(` |____| `));
console.log(arr5.join(` !____! `));
console.log(arr6.join(` ^____^ `));
console.log(`++++++++++++++++++++++++++++++++++++++`);
