console.log(`----------search()-----------`);
console.log(a.search('K.'));
console.log(c.search('K.'));
console.log(d.search('K.'));
console.log(e.search('K.'));
console.log(f.search('K.'));
console.log(g.search(' '));
console.log(h.search('K.'));
console.log(i.search('vm'));
console.log(j.search('t'));
console.log(k.search('l'));
console.log(`++++++++++++++++++++++++++++++++++++++`);
